### ISSUE TITLE
Can't add text

### ISSUE THREAD

**Issue by Xlecronia** [ImagicalGamer/Texter#7]
When I try to add text, it says an unknown error occurred and console gives this error. 
31.03 10:02:58 [Server] INFO Error: "Call to undefined method pocketmine\Player::addParticle()" (EXCEPTION) in "myzip:///Texter-master.zip#Texter-master/src/Texter/Main" at line 51
31.03 10:02:58 [Server] INFO Unhandled exception executing command 'texter' in texter: Call to undefined method pocketmine\Player::addParticle()

**Comment by ImagicalGamer** [comment]
Known issue this plug is still under development.

**Comment by Xlecronia** [comment]
Oh okay!
